[package]
name = "doc-signer"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "0.17.8"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22.1"

